'''


Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

'''

pentagon_numbers=[]
for n in range(1,1000000):
    pentagon_number=n*(3*n-1)/2
    pentagon_numbers.append(pentagon_number)
found=False
for i in pentagon_numbers:
    if found:
        break
    for j in pentagon_numbers:
        if i+j in pentagon_numbers and abs(j-i) in pentagon_numbers:
            print(i,j,i+j,abs(j-i))
            found=True
            break
            
print(pentagon_numbers)